name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Build app
        run: ./scripts/buildprod.sh

      - name: Migrate DB
        run: ./scripts/migrateup.sh

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud builds submit --tag europe-west3-docker.pkg.dev/notely-454808/notely-ar-repo/notely:latest .'

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image europe-west3-docker.pkg.dev/notely-454808/notely-ar-repo/notely:latest --region europe-west3 --allow-unauthenticated --project notely-454808 --max-instances=4
